In [1]:
import numpy as np

In [6]:
# creat matrix with randam no. 10 to 50
arr=np.random.randint(10,50,(3,4))
arr

array([[24, 18, 32, 23],
       [22, 22, 47, 24],
       [25, 19, 38, 34]], dtype=int32)

In [9]:
# creat matrix with exualy divide
np.linspace(10,50,12).round(2)


array([10.  , 13.64, 17.27, 20.91, 24.55, 28.18, 31.82, 35.45, 39.09,
       42.73, 46.36, 50.  ])

In [10]:
arr

array([[24, 18, 32, 23],
       [22, 22, 47, 24],
       [25, 19, 38, 34]], dtype=int32)

In [14]:
# maxium by column
np.max(arr,axis=0)

array([25, 22, 47, 34], dtype=int32)

In [15]:
# max by rows
np.max(arr,axis=1)

array([32, 47, 38], dtype=int32)

In [16]:
# max value by position 
np.argmax(arr,axis=1)

array([2, 2, 2])

In [18]:
array=([[24, 18, 32, 23],
       [22, 22, 47, 24],
       [25, 19, 38, 34]],)
array

([[24, 18, 32, 23], [22, 22, 47, 24], [25, 19, 38, 34]],)

In [20]:
arr1=array
arr1

([[24, 18, 32, 23], [22, 22, 47, 24], [25, 19, 38, 34]],)

In [32]:
arr[1,0]

np.int32(22)

In [34]:
arr[0:2,0:2]

array([[24, 18],
       [22, 22]], dtype=int32)

In [37]:
arr[1:,1:3]

array([[22, 47],
       [19, 38]], dtype=int32)

In [38]:
# even index row and odd index col
arr[::2,1::2]

array([[18, 23],
       [19, 34]], dtype=int32)

In [39]:
# tronspose the matrix
arr.transpose()

array([[24, 22, 25],
       [18, 22, 19],
       [32, 47, 38],
       [23, 24, 34]], dtype=int32)

In [42]:
# reverse the matrix
arr[::-1,::-1]

array([[34, 38, 19, 25],
       [24, 47, 22, 22],
       [23, 32, 18, 24]], dtype=int32)

In [43]:
# normalize the value in btw range 0 and 1
# x-min/max-min
new=(arr1-arr.min())/(arr.max()-arr.min())
new

array([[[0.20689655, 0.        , 0.48275862, 0.17241379],
        [0.13793103, 0.13793103, 1.        , 0.20689655],
        [0.24137931, 0.03448276, 0.68965517, 0.55172414]]])

In [44]:
new.round(2)

array([[[0.21, 0.  , 0.48, 0.17],
        [0.14, 0.14, 1.  , 0.21],
        [0.24, 0.03, 0.69, 0.55]]])

In [48]:
new=arr>30
new

array([[False, False,  True, False],
       [False, False,  True, False],
       [False, False,  True,  True]])

In [49]:
arr[arr>30]

array([32, 47, 38, 34], dtype=int32)

In [51]:
arr1=[23,-56,39,-10,-12,45,-15]
arr1

[23, -56, 39, -10, -12, 45, -15]

In [55]:
arr1[arr1<0]=0
arr1

TypeError: '<' not supported between instances of 'list' and 'int'