In [2]:
l1 = [2,5,7,3,9]
l1+[4]

[2, 5, 7, 3, 9, 4]

In [3]:
import numpy as np

In [4]:
a1 = np.array([2,5,7,3,9])
a1+4

array([ 6,  9, 11,  7, 13])

what is numpy ?
it is a powerful python library used for
*numerical computations
*working with arrays and matrices
*mathematical operations
*data science and machine learning

Advantage of numpy
*faster then python list
*uses less memory
*support multi-dimensional arrays
*large collections of mathematical function 

List vs array:
1.list we cannot do element wise operation but in array we can do .
2.array to list convertion is possible and also list to array convertion also possible but it will loss the dimenstiom
3.list is hetirogenious datatype but numpy is a homogenous datatype


In [5]:
import numpy as np

In [6]:
a1= np.array(['python',45,89,12.6,30.27,True])
a1

array(['python', '45', '89', '12.6', '30.27', 'True'], dtype='<U32')

In [9]:
a1= np.array([45,89,12,30,])

In [10]:
a1.shape

(4,)

In [18]:
len(a2)

2

In [19]:
type(a2)

numpy.ndarray

In [22]:
a2,dtype

NameError: name 'dtype' is not defined

In [25]:
np.zeros((3,3),dtype= 'int')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [26]:
np.full((3,4),8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [29]:
np.identity(3,dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [30]:
np.eye(3,dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [32]:
arr1=np.arange(1,10,1)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.reshape(arr1,(3,3),order = 'F')

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [38]:
# creat even array from 1 to 20
arr2=np.arange(2,21,2)
arr2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [39]:
# creat odd array from 1 to 20
arr3=np.arange(1,21,2)
arr3

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [42]:
arr4=np.random.rand(4,5).round(2)
arr4

array([[0.05, 0.06, 0.63, 0.69, 0.03],
       [0.25, 0.23, 0.25, 0.74, 0.92],
       [0.22, 0.05, 0.77, 0.11, 0.26],
       [0.35, 0.06, 0.28, 0.5 , 0.42]])

In [45]:
arr5=np.random.randint(1,100,(4,5))
arr5

array([[63, 27, 21, 95, 85],
       [39, 60, 19, 71, 24],
       [67, 62,  5, 18, 71],
       [96, 92, 37, 24, 55]], dtype=int32)

In [46]:
arr5.max()

np.int32(96)